# Generated by Django 5.0.7 on 2024-08-20 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autos_model',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1f20f2a5-84b5-4d1e-b0eb-160c3fd6acd5'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('car_brand', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
