# Generated by Django 5.0.7 on 2024-10-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_autocomments_autosmodel_profile_profilecomments_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoComments',
            new_name='AutoComment',
        ),
        migrations.RenameModel(
            old_name='ProfileComments',
            new_name='ProfileComment',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
