# Generated by Django 5.0.7 on 2024-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_rename_autocomments_autocomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosmodel',
            name='featured_image',
            field=models.ImageField(blank=True, default='default-auto.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='featured_image',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to=''),
        ),
    ]
