# Generated by Django 5.0.7 on 2024-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_autosmodel_featured_image_user_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosmodel',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='autosmodel',
            name='source_link',
        ),
        migrations.AddField(
            model_name='autosmodel',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='autosmodel',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
