# Generated by Django 5.0.7 on 2024-12-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0007_alter_autocomment_from_user_and_more'),
        ('users', '0010_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocomment',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
