# Generated by Django 5.0.7 on 2024-12-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0008_alter_autocomment_from_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autosmodel',
            options={'ordering': ['-vote_ratio', '-vote_total', 'car_brand', 'car_model']},
        ),
    ]
