# Generated by Django 5.0.7 on 2024-12-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0011_auction_bid_auctionhistory'),
        ('users', '0014_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='auctionhistory',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='auctionhistory',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.AlterField(
            model_name='autosmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='AuctionHistory',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
