# Generated by Django 5.0.7 on 2024-12-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0012_remove_bid_auction_remove_auctionhistory_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autocomment',
            name='topic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
