# Generated by Django 5.0.7 on 2024-11-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
