# Generated by Django 5.0.7 on 2024-11-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_short_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='advantages',
            field=models.ManyToManyField(blank=True, to='users.advantage'),
        ),
    ]
