# Generated by Django 5.0.7 on 2024-11-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_advantage_profile_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
