# Generated by Django 5.0.7 on 2024-12-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_telegram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_youtube',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
