# Generated by Django 5.0.7 on 2024-12-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_social_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
