# Generated by Django 5.0.7 on 2024-12-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecomment',
            name='topic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
