# Generated by Django 5.0.7 on 2024-12-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_rename_starting_price_auction_start_price'),
        ('users', '0014_message_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('featured_image', models.ImageField(blank=True, default='default-auto.jpg', null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
