# Generated by Django 5.0.7 on 2024-12-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auctioncar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auctioncar'),
        ),
    ]
