# Generated by Django 5.0.7 on 2024-12-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_auction_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioncar',
            name='start_price',
        ),
    ]
