# Generated by Django 5.0.7 on 2024-12-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_auctioncar_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
