# Generated by Django 5.0.7 on 2024-12-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auction_like_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionHistory',
        ),
    ]
